let canvas = document.querySelector('canvas');
let ctx = canvas.getContext('2d');
ctx.moveTo(0,0);
ctx.lineTo(200,100);
ctx.stroke();
ctx.beginPath();
ctx.arc(100, 100, 50, 0, 2 * Math.PI);
ctx.strokeStyle = 'red';
ctx.stroke();
ctx.font = '30px Arial';
ctx.fillText('fuck you canvas', 30, 50);
ctx.strokeText('fuck you canvas', 30, 100);
ctx.fillStyle = '#ff0';
ctx.fillRect(10, 10, 10, 10);